### ISSUE TITLE
how-to-npm,lession 10,dist-tag

### ISSUE THREAD

**Issue by kkkeny** [nodeschool/discussions#995]
How to use npm dist-tag add xx@xx?
I got this:
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "dist-tag" "add" "next@2.0.0"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! code E404

npm ERR! 404 missing : -/package/next/dist-tags

**Comment by martinheidegger** [comment]
seems like this has been fixed recently?! https://github.com/npm/how-to-npm/commit/d75557b7d201c92ba88bc07752fb81427738b3b4 maybe you need to install a newer version?

**Comment by jesantana** [comment]
I have exactly the same problem

I have npm 2.7.5

**Comment by martinheidegger** [comment]
@jesantana what version of how-to-npm do you have?

**Comment by jesantana** [comment]
I have 1.2.0. Just downloaded it yesterday.

**Comment by martinheidegger** [comment]
cc @linclark

**Comment by kkkeny** [comment]
hi there,
I set a global registry to npm.
after removed it,solved.
I think it's a bug on how-to-npm.

**Comment by martinheidegger** [comment]
@kkkeny Can you post a bug to "how-to-npm"?

**Comment by jvhensley** [comment]
Hi! I entered this and got these errors:
jvhensley@npm:~/workspace $ npm dist-tag add package.json@1.0.0 [beta]
npm ERR! Linux 3.14.13-c9
npm ERR! argv "node" "/home/ubuntu/.nvm/v0.10.35/bin/npm" "dist-tag" "add" "package.json@1.0.0" "[beta]"
npm ERR! node v0.10.35
npm ERR! npm  v2.9.1
npm ERR! code E404

npm ERR! 404 missing : -/package/package.json/dist-tags

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

===========
the instruction are so vague, I don't even know if I'm entering the command correctly. Please help! I have the most up-to-date NPM, because I just installed it today, and verified it.

**Comment by bernardodesousa** [comment]
Same/similar problem here.

* Windows 8.1
* Node v0.12.4
* npm v2.11.0

The title says lesson 10, but for me, the Dist Tag lesson is the 11th. Different how-to-npm version?

I'll skip to next tutorial, but really don't like to leave things undone :P

> C:\node-js-getting-started\how-to-npm>npm dist-tag add new-package@1.0.2 [stable
]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\SOUSA\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "dist-tag" "add" "new-package@1.0.2" "[stable]"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.0
npm ERR! code E404

>npm ERR! 404 missing : -/package/new-package/dist-tags

>npm ERR! Please include the following file with any support request:
npm ERR!     C:\node-js-getting-started\how-to-npm\npm-debug.log

**Comment by kravasb** [comment]
Seems like the same issue for me (Mac OS Yosemite 10.10.3, Node.JS v. 0.12.4; NPM v. 2.11.0):

```
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/OKravchuk/Study/NodeSchool/how-to-npm/npm-debug.log
Oleksandrs-MacBook-Pro:how-to-npm OKravchuk$ mkdir dist-tags
Oleksandrs-MacBook-Pro:how-to-npm OKravchuk$ npm dist-tag add how-to-npm@1.0.1 qa
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "dist-tag" "add" "how-to-npm@1.0.1" "qa"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.0
npm ERR! code E404

npm ERR! 404 missing : -/package/how-to-npm/dist-tags

npm ERR! Please include the following file with any support request:
npm ERR!     

/Users/OKravchuk/Study/NodeSchool/how-to-npm/npm-debug.log
```

npm-debug.log content:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'dist-tag',
1 verbose cli   'add',
1 verbose cli   'how-to-npm@1.0.1',
1 verbose cli   'qa' ]
2 info using npm@2.11.0
3 info using node@v0.12.4
4 verbose dist-tag add qa to how-to-npm@1.0.1
5 silly mapToRegistry name how-to-npm
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry http://localhost:15443/
8 silly mapToRegistry uri http://localhost:15443/how-to-npm
9 verbose request uri http://localhost:15443/-/package/how-to-npm/dist-tags
10 verbose request no auth needed
11 info attempt registry request try #1 at 6:34:56 PM
12 verbose request id 1d32febd06c10a7a
13 http request GET http://localhost:15443/-/package/how-to-npm/dist-tags
14 http 404 http://localhost:15443/-/package/how-to-npm/dist-tags
15 verbose headers { 'content-type': 'application/json',
15 verbose headers   date: 'Sun, 31 May 2015 15:34:56 GMT',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'transfer-encoding': 'chunked' }
16 verbose stack Error: missing : -/package/how-to-npm/dist-tags
16 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
16 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
16 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:368:22)
16 verbose stack     at Request.emit (events.js:110:17)
16 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1219:14)
16 verbose stack     at Request.emit (events.js:129:20)
16 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1167:12)
16 verbose stack     at IncomingMessage.emit (events.js:129:20)
16 verbose stack     at _stream_readable.js:908:16
16 verbose stack     at process._tickCallback (node.js:355:11)
17 verbose statusCode 404
18 verbose cwd /Users/OKravchuk/Study/NodeSchool/how-to-npm
19 error Darwin 14.3.0
20 error argv "node" "/usr/local/bin/npm" "dist-tag" "add" "how-to-npm@1.0.1" "qa"
21 error node v0.12.4
22 error npm  v2.11.0
23 error code E404
24 error 404 missing : -/package/how-to-npm/dist-tags
25 verbose exit [ 1, true ]
```

**Comment by RamiAwar** [comment]
same thing with me. Im on a mac as well.

**Comment by zachfedor** [comment]
I figured out the issue but it took a while. Using `npm help dist-tag` didn't help as much as I wanted. It says that the command is used like so `npm dist-tag add <pkg>@<version> [<tag>]` but there are no examples to provide an idea of formatting. Use this instead:

    npm dist-tag add @zachfedor/how-to-npm@1.0.1 test

Where `zachfedor` is your npm username, `how-to-npm` is your package name, `1.0.1` is the package version you want to modify, and `test` is the tag you are adding.

**Comment by alexeyleonov** [comment]
I tried with "npm dist-tag add @<username>/<pkg name>@<version>" on win7, but it's not working with me.

**Comment by dkoleary88** [comment]
Same issue here and I've tried the above mentioned format

**Comment by coloradude** [comment]
I had this same problem last time I tried doing this way back in March or something and it's still not explained any better.

**Comment by azaroma** [comment]
**npm** version 2.14.2 **node** version 0.12.7 same issue. The @zachfedor method outputs this:

        npm ERR! Usage:
        npm ERR! npm dist-tag add <pkg>@<version> [<tag>]
        npm ERR! npm dist-tag rm <pkg> <tag>
        npm ERR! npm dist-tag ls [<pkg>]

how-to-npm states that i have only one tag, but `npm dist-tag ls` output:

        npm ERR! dist-tag ls Couldn't get dist-tag data for fiction
        npm ERR! Linux 4.1.6-1-ARCH
        npm ERR! argv "node" "/usr/bin/npm" "dist-tag" "ls"
        npm ERR! node v0.12.7
        npm ERR! npm  v2.14.2
        npm ERR! code E404
        
       npm ERR! 404 missing : -/package/fiction/dist-tags
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /home/lazaro/nodeschool/how to npm/npm-debug.log

**Comment by velmuruganvelayutham** [comment]
I am also facing this issue !.. any workaround for this ?

**Comment by efreethy** [comment]
Facing the same issue. None of the recommended combinations of usernames, package names, and version numbers are working for me. Sigh....

**Comment by StevenXL** [comment]
I've had this issue for some time now (years). Is it still not fixed? I've tried all of the above suggestions.

**Comment by interglobalmedia** [comment]
Hi,

I think there is still a bug. I have tried everything, including a suggestion on Stack Overflow, but I get a 404 error. This is what I did and got back:

npm dist-tag add how-to-npm@0.0.2                                                   ⏎ ✹ ✭
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "dist-tag" "add" "how-to-npm@0.0.2"
npm ERR! node v5.9.0
npm ERR! npm  v3.8.2
npm ERR! code E404

npm ERR! 404 missing : -/package/how-to-npm/dist-tags

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mariacam/Development/bitbucket-repos/how-to-npm/npm-debug.log

Any suggestions? Thanks!

**Comment by rwrenjr** [comment]
Make sure you are logged in to npm first and it should work:

MacBook:how-to-npm robertwrenjr$ npm dist-tag add @linclark/pkg@1.0.2 ["dev"]
+[dev]: @linclark/pkg@1.0.2
MacBook:how-to-npm robertwrenjr$ how-to-npm verify
Congratulations!  You've added a dist-tag!

**Comment by starkraving** [comment]
This worked for me:

$ mkdir dist-tags
$ nds dist-tag add @<username>/<pkg>@<version> <tagname>

After I found this page to get the syntax correct, I started getting an error saying "Registry returned 403 for PUT"; manually creating the folder <pkg>/dist-tags worked for me, though I did have to try a different version number for the dist-tag command than I used when I got the error.

HTH

**Comment by erezLieberman** [comment]
same problem here:
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/npm" "dist-tag" "add" "mypack@1.0.0" "test"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.6
npm ERR! code E404

npm ERR! 404 missing : -/package/mypack/dist-tags

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/dev_folder/npm-debug.log

**Comment by angelantonio** [comment]
i tried making a directory for dist-tags and it worked for @linclark/pkg but "how-to-npm verify" gives me this error:

module.js:327
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/.config/how-to-npm/registry/angelantoniopackage/body.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.exports.verify (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/problems/11-dist-tag.js:42:14)
    at Shop.verify (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:409:26)

**Comment by Mycroft1891** [comment]
@robertwrenjr was right.
I got this error because I tried to add the dist-tag to my package but we have to use the linkclark package:

`npm dist-tag add @linclark/pkg@1.0.2 ["dev"]`

This fixed it for me.

**Comment by TheWhippinpost** [comment]
Tried: npm dist-tag add @linclark/pkg@1.0.2 ["dev"]

multiple times with different tags, which seemed to work, but: how-to-npm verify

Returned:
                                  
"Uh oh, looks like you still only have a single dist-tag.
Use `npm help dist-tag` to learn how to add another one."

**Comment by hungdomanh** [comment]
@Mycroft1891  Thank you! I have finished :)

**Comment by dalenguyen** [comment]
Got the same problem. I remove everything by using the command

`rm -rf * `

in the app folder. After that, I redo the how-to-npm.  Just make sure when you run 

`npm init --scope=<username>`

Keep the default appname with your username on it (e.g: @dalenguyen/myapp)

It works for me.

**Comment by sw-yx** [comment]
@zachfedor just wanted to thank you for potentially rescuing me from the brink of giving up. i hate hate hate how poorly written the error message is.

**Comment by sonichanxiao** [comment]
Still have problem, I am up to "Dist Tag".
Here is my npm version:
{ 'npm-dev': '1.0.4',
  npm: '4.0.5',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '46',
  node: '4.6.1',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '4.5.103.37',
  zlib: '1.2.8' }

And here is the npm dist-tag ls @linclark/pkg
latest: 1.0.1
testtag1: 1.0.2
testtag2: 1.0.3

I guess I have more than one tag already, so I run how-to-npm verify, it still says:
Uh oh, looks like you still only have a single dist-tag.
Use `npm help dist-tag` to learn how to add another one.

What I did wrong? Thanks in advance.

**Comment by angelantonio** [comment]
I have the same problem. Any solution for this?

Angel Antonio
787-453-7873

On Jan 1, 2017, at 6:06 PM, Xiao <notifications@github.com<mailto:notifications@github.com>> wrote:


Still have problem, I am up to "Dist Tag".
Here is my npm version:
{ 'npm-dev': '1.0.4',
npm: '4.0.5',
ares: '1.10.1-DEV',
http_parser: '2.7.0',
icu: '56.1',
modules: '46',
node: '4.6.1',
openssl: '1.0.2j',
uv: '1.9.1',
v8: '4.5.103.37',
zlib: '1.2.8' }

And here is the npm dist-tag ls @linclark/pkg
latest: 1.0.1
testtag1: 1.0.2
testtag2: 1.0.3

I guess I have more than one tag already, so I run how-to-npm verify, it still says:
Uh oh, looks like you still only have a single dist-tag.
Use npm help dist-tag to learn how to add another one.

What I did wrong? Thanks in advance.

-

**Comment by sonichanxiao** [comment]
I guess restart from the beginning might be able to avoid any
unnoticed mistake made earlier.

Regards


Xiao Han

**Comment by ChaosPredictor** [comment]
chaospredictor:~/workspace/e01 $ npm ls
@chaospredictor/e01@1.0.1 /home/ubuntu/workspace/e01
└── @linclark/pkg@1.0.2
chaospredictor:~/workspace/e01 $ npm dist-tag add @chaospredictor/e01@1.0.1 [beta]

it's work for me

**Comment by KoniKodes** [comment]
I had to take the brackets off of [beta]

**Comment by nalcus** [comment]
i was forgetting to add brackets. when i added them [latest] it worked fine

**Comment by KoniKodes** [comment]
Isn't it funny how they both worked, but different for each of us?

**Comment by Ronalses** [comment]
This worked for me
npm dist-tag add @linclark/pkg@1.0.1 beta

Regards!!

**Comment by nachtmaal** [comment]
I came across the same error and it was caused because I tried to add the dist-tag to the version 1.0.1 which never existed since my package started from version 1.0.0 and during the version tutorial after I updated the version to 1.0.1 it said I did not update the version (I did from 1.0.0 to 1.0.1) so I had to update it to 1.0.2 to proceed.

**After running the command on version 1.0.0 it worked.**

**Comment by ook4mi** [comment]
Thanks @nachtmaal your solution fixed my problem ;)

**Comment by Madninja1** [comment]
So i did another way, maybe it will be usefull, at first I run comand "npm ls" copy my acc name and version: axample- name@1.2.3
Then write next comand "npm dist-tag add name@1.2.3 test"
So this works for me)

**Comment by shadeland** [comment]
Same problem here: ` Ubuntu 16.04 LTS , node v6.1.0, npm 4.5.0, how-to-npm 2.4.2 `

```
npm ERR! code E404
npm ERR! 404 missing : -/package/@shadeland%2fnpming/dist-tags

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adel/.npm/_logs/2017-05-04T18_35_58_537Z-debug.log

```
adding username doesn't work. 
'hwo-to-npm verify' and 'how-to-npm verify SKIP' give me this error: 

```
Could not verify: Error: Cannot find module '/home/adel/.config/how-to-npm/registry/@shadeland/npming/body.json'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.exports.verify (/home/adel/.nvm/versions/node/v6.1.0/lib/node_modules/how-to-npm/problems/11-dist-tag/index.js:22:14)
    at LegacyAdventure.WA.executeExercise (/home/adel/.nvm/versions/node/v6.1.0/lib/node_modules/how-to-npm/node_modules/workshopper-adventure/index.js:425:16)
    at LegacyAdventure.WA.process (/home/adel/.nvm/versions/node/v6.1.0/lib/node_modules/how-to-npm/node_modules/workshopper-adventure/index.js:317:17)
    at LegacyAdventure.WA.verify (/home/adel/.nvm/versions/node/v6.1.0/lib/node_modules/how-to-npm/node_modules/workshopper-adventure/index.js:258:15)
    at Object.exports.handler.exports.handler [as handler] (/home/adel/.nvm/versions/node/v6.1.0/lib/node_modules/how-to-npm/node_modules/workshopper-adventure/lib/commands/verify.js:12:21)
    at Object.explicit.execute.$ (/home/adel/.nvm/versions/node/v6.1.0/lib/node_modules/how-to-npm/node_modules/commandico/commandico.js:143:15)
```

**Comment by Maygus** [comment]
The following worked for me.
`npm dist-tag add package@2.1.4 ["beta"]`
Using a mixture of above appears I needed to put the name of my JSON file before the "@" and encapsulate the beat tags.

**Comment by FabioRam** [comment]
The following worked for me.
npm dist-tag add @<author>/<package>@<version> <tag>

**Comment by bemyhre** [comment]
@FabioRam's solution also worked for me.

**Comment by manika1511** [comment]
This worked for me:
npm dist-tag add **@<username>/<name of package you published>@<version>** ["dev"]

you can get the above bold portion on running npm ls... The main package is the one..
You can check the creation of dist-tag by running: npm dist-tag ls

**Comment by manika1511** [comment]
@FabioRam's solution worked for me too

**Comment by ThadeusAjayi** [comment]
From my troubles, I guess its a bug that falls through and then the code works randomly. This worked for me: `npm dist-tag add thadeus@1.1.0 beta`
"thadeus" happens to be my package name and 1.1.0 is the same version am making a variant of.
I hope it makes sense.

**Comment by arpithapatil** [comment]
I faced the same trouble.
I ran `npm dist-tag add <packagename/pkg>@<version> <tagname>`
And this worked for me. I think we should add the word "pkg" at the end of the name of the package in the command.

Hope this helps. Thanks.

**Comment by Anna-Myzukina** [comment]
this help me
npm dist-tag add @linclark/pkg@1.0.2 ["dev"]
