### ISSUE TITLE
 js-best-practices select 0 giving below error. Not able to download vendingMachine.js file

### ISSUE THREAD

**Issue by ankit-mehrotra** [nodeschool/discussions#2258]
# Getting Started

  The goal of this workshopper is to help you learn how to create a
  resilient codebase using best practices. The workshopper will guide you
  through some exercises which will have you make incremental improvements
  to a bad codebase. Through the exercises, you will learn best practices to
  help keep your code maintainable, as well as some bad practices to avoid.

  You will be making changes to a vending machine app. You will be given a
  file called vendingMachine.js as well as a few other empty js files. The
  next few excercises will have you break down the vending machine into a
  program that still functions the same but is easier to maintain, test, and
  update.

  When you exit this instructions screen, the files necessary for the
  exercises will be downloaded for you.

press any key to continue...
(node:9984) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: process.stdin.setRawMode is not a function

**Comment by ankit-mehrotra** [comment]
Used cmd prmt instead of bash..
https://github.com/workshopper/stream-adventure/issues/171
